[window]

dimensions = {columns = 100, lines = 30}
opacity = 0.8
blur = false

[font]
size = 12.0

[font.bold]
family= "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family= "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family= "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family= "JetBrainsMono Nerd Font"
style = "Regular"


[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
]

